### ISSUE TITLE
Question: If the scopes are omitted during the DCR process?

### ISSUE THREAD

**Issue by TakahikoKawasaki** [OpenBanking-Brasil/specs-seguranca#106]
"[7.2. Regulatory Roles to OpenID and OAuth 2.0 Mappings](https://openbanking-brasil.github.io/specs-seguranca/open-banking-brasil-dynamic-client-registration-1_ID1.html#name-regulatory-roles-to-openid-)" of "[Open Banking Brasil Financial-grade API Dynamic Client Registration 1.0 Implementers Draft 1](https://openbanking-brasil.github.io/specs-seguranca/open-banking-brasil-dynamic-client-registration-1_ID1.html)" states as follows.

>**If the scopes are omitted during the DCR process**, the authorization server shall grant the complete set of potential scopes based on the registering bank's regulatory roles, as described in the Server Defaults section.

However, there is no client metadata which specifies scopes. How should the requirement above be interpreted? For example, like below?

> When an authorization request does not contain scopes, the authorization server should compute default scopes based on the `software_roles` client metadata of the client application and assign the scopes to the access token being issued.

Should "during the DCR process" be replaced with "during an authorization request"?

**Comment by TakahikoKawasaki** [comment]
FYI: The 9th clause in "[7.1. Authorization server](https://openbanking-brasil.github.io/specs-seguranca/open-banking-brasil-dynamic-client-registration-1_ID1.html#name-authorization-server-2)" states as follows.

> shall validate that requested scopes are appropriate for the softwares authorized regulatory roles;

The validation in the clause cannot be performed during the client registration process because, as I mentioned above, there is no way to request scopes during a client registration process. If we had to perform the validation, it would have to be done during an authorization request process.

**Comment by RalphBragg** [comment]
Why is there no way to request scopes during a registration process?

**Comment by TakahikoKawasaki** [comment]
Thank you for showing pointers to the specifications of UK Open Banking and AU CDR that define `scope` client metadata. That is, we don't have a global standard that defines default scopes per client yet.

It should be described somewhere concretely with examples how to compute scopes for each access token. Otherwise, confusion like below would happen and it would become difficult to expect interoperable behaviors.

----------

If a client has the role "PAGTO" whose allowed scopes are `openid`, `payments` and `consents`, what should happen when the client makes an authorization request whose `scope` is `openid payments accounts my_scope`? Candidates would be like below.

|No.|Scopes|Description|
|:--|:--|:--|
|1|`openid payments accounts my_scope`|Equal to `scope` in the authorization request|
|2|`openid payments my_scope`|Drop `accounts` because the set of allowed scopes for "PAGTO" does not include `accounts` although `accounts` is a standardized scope in OBB, but keep `my_scope` because it is a custom scope defined locally by the deployment|
|3|`openid payments`|Intersection of `scope` in the authorization request and the set of allowed scopes for "PAGTO"|
|4|`openid payments consents`|Ignore `scope` in the authorization request and use the set of allowed scopes for "PAGTO"|
|5|???|Just rely on the consent (what is the logic?)|

What if a client has two or more roles like "DADOS" and "PAGTO" (as the example in OBB DCR Section 8.1 shows)? What if `scope` in the authorization request includes `payments` which is in the set of allowed scopes for "PAGTO" but is not in the set of allowed scopes for "DADOS"?

If _"Banks can ignore scopes entirely and just rely on the consent"_, what is the logic? In that case, when should authorization server implementations refer to the table in OBB DCR Section 7.2 for what purposes?

**Comment by RalphBragg** [comment]
You're welcome however there is  limited additional guidance that can be given as the GT Security have adopted a mixture of 'scope' and 'authorization_details' (consent content) for controlling access to resource. The formal functional API of the swagger specifications for the resource APIs also mandate different scopes are required for different resources. This means that TPPs could ask for certain scopes when wishing to access specific resources in addition to the 'authorization_details' however the FAPI WG has been quite clear that 'scope' can be conveyed either as 'scope' strings or as 'authorization_details' which is what the consent resource is and that it is the Authorisation Servers responsibility to ensure that Access Tokens are issued that actually grant access to resources that the resource owns and the third party has consent to access.

So this presents a problem in that the functional api specification for brazil actually contradicts this direction from FAPI WG so guidance have been added to try and address this ambiguity. I have raised this several times which is why the best that could be agreed was to ensure that the the AS always grants an access token that can give Third Parties access to the resources that the consumer has requested in the consent.

To your specific examples.

What if a client has two or more roles like DADOS or PAGTO. Then the client can request a scope of access to resources that cover both payments and account information. Both in the authorisation details (consent payload and via the scopes).

From the table; 
1. Yes you could grant these 'scopes' if you wanted to however the customer only consents to the PERMISSIONS in the Consent Object so they have no LGPD (GDPR) impact, nor do 'scopes' actually control access to consumer resources.

2. Again, yes if you wanted to drop the requested accounts scope because the consumer created a consent that only had PERMISSIONS in the Consent resources for DADOS PERMISSIONS then you could drop these scopes.

3. Yes, however again, you could drop payments if you wanted too provided your resource server honoured the Authorization details with the scope in it.

4. Yes again, provided the TPP is a DADOs and they have requested a set of PERMISSIONS that are explicitly for DADOS and a Banks Resource Server will accept an AT without these scopes for access to the resources then this again would OK.

One issue is it appears that a lot of implementations of Banks Resource Servers can not rely on the Authorisation Details alone and want these scopes also added. Another issue is that some Banks Authorisation Servers can not apply or determine default scope at the point of authorisation and so define the scopes on registration that a TPP can ask for based on their regulatory roles.

You will need to work with your Banks Resource server to determine what path is best for your bank. I will continue to suggest dropping all of these unnecessary additional scopes for controlling access to resources.

Some worked examples:

1. Consent: [ACCOUNTS_READ, CREDIT_CARDS_ACCOUNTS_READ]
2. GDPR with Customer: As per the definition of those permissions
3. Consent Reference Id (Authorisation Details Created) - a Bank can reject any permissions 

In order to create the above Consent Resource, the Client must have access to scope 'consents' according to the consent API specification however given that they are regulatory defined as a DADOS they MUST.

During Authorization, a client conveys the authorisation details in a dynamic scope which it must be able to request and access. The following error conditions exist but are not documented by the Security GT at this time.

- Referred consent Id doesn't exist
- Referred consentId was created by a different client.
- Referred consent logged User was a different user to the one that just authenticated.

The reference bank handles all of these in a detailed fashion but the error codes are not defined by the GT Security for ID1. 

Authorisation Details vs Scopes

Assuming that the client and the subject own the authorisation details that are being processed

- If the TPP didn't ask for the resource scopes for 'accounts' and 'credit-cards-accounts' resources however the consumer has consented to the correct permissions it is still the banks responsibility to ensure that the issued access token has the 'correct scope' to access what has been consented too. This position was adopted by the FAPI WG as there is sufficient scoping in the authorisation details alone. scopes are superfluous.

This however may cause issue for you Banks Resource Server so you may have to 'ammend' the fixed scope strings to match the permissions in the authorisation details if your banks resource server requires it.

**Comment by TakahikoKawasaki** [comment]
@RalphBragg Thank you for taking time to write up the detailed comment. It sounds that each bank has to decide details. Also, the process of access token issurance has to look into details of "consent" in order to assign scopes properly to access tokens.

**Comment by TakahikoKawasaki** [comment]
Very sorry. My mistake. RFC 7591 defines `scope` client metadata...

>   scope
>      String containing a space-separated list of scope values (as
>      described in Section 3.3 of OAuth 2.0 [RFC6749]) that the client
>      can use when requesting access tokens.  The semantics of values in
>      this list are service specific.  If omitted, an authorization
>      server MAY register a client with a default set of scopes.

It seems that the relationship between the `scope` client metadata and the `scopes_supported` server metadata is similar to the relationship between the `grant_types` client metadata and the `grant_types_supported` server metadata.
