### ISSUE TITLE
Should cnpj be mandatory?

### ISSUE THREAD

**Issue by bruno-ortizgb** [OpenBanking-Brasil/specs-seguranca#112]
The spec currently states the following:

> Requesting the "cnpj" Claim
This profile defines "cnpj" as a new standard claim as per clause 5.1[OIDC]

But the organization where i work does not work with cnpj so making it mandatory is a issue.

Should we make the cnpj a optional claim for the ASPSP's?

**Comment by DeiGratia33** [comment]
Does your organization work with business accounts or just personal accounts? The CNPJ is the standard claim when handling business accounts.

**Comment by RalphBragg** [comment]
The issue is that the specification requires Banks to support the CNPJ claim. It doesn't distinguish between banks that don't support business accounts. 

shall support the oidc standard claim "cnpj" as defined in clause 5.2.2.3 of this document

needs to read

shall support the oidc standard claim "cnpj" as defined in clause 5.2.2.3 of this document if offering services to corporate customer.

shall support the oidc standard claim "cpf" as defined in clause 5.2.2.3 of this document if offering services to individual or personal customers.

Or similiar reading.

**Comment by DeiGratia33** [comment]
I see this is implicit, but at the same time just wanted to confirm we are not handling with a scenario where the entity have a business account that is not linked by CNPJ. This would be very peculiar if possible.

**Comment by bruno-ortizgb** [comment]
@DeiGratia33 we just work with personal accounts, i agree with @RalphBragg on how the specification could be changed.

It's not implicit if the certification test enforces that we need to support both claims even if we dont work with them.

**Comment by RalphBragg** [comment]
I'll raise a PR.

**Comment by RalphBragg** [comment]
PR Raised and out for review
