### ISSUE TITLE
broken reference on API sec id1

### ISSUE THREAD

**Issue by dcreado** [OpenBanking-Brasil/specs-seguranca#150]
Hi All,

the API Security Profile 1.0 ID 1 document on section 5.2.1 refers to a section 7.4.1 on FAPI 1.0 Advanced that was withdrawn.

**Comment by DeiGratia33** [comment]
That is correct.

**Comment by RalphBragg** [comment]
This should be referring to 7.4.1 Baseline not advanced which calls out that FAPI does not require encrypted request objects.

**Comment by RalphBragg** [comment]
Thanks for the spot at @dcreado - this documentation reference has been updated to FAPI 1 Baseline instead of Advanced where this issue has been identified.
For reference; i've raised bug https://bitbucket.org/openid/fapi/issues/428/baseline-clause-741-talks-about-security against FAPI 1 Baseline which is in Final but this issue should be addressed in an Errata release as it is addressing informational points only.
