### ISSUE TITLE
Attribute details

### ISSUE THREAD

**Issue by andreborges01** [OpenBanking-Brasil/specs-seguranca#16]
It is important to get more detail on both guides, especially the attributes of the token (`refresh_token` and` access_token`). Security profile must specify the requirements for authorizaition_code, including it´s expiration time and response in case of error or timeout. It is necessary to explain all the attributes of the tokens, endpoints, request objets and responses.

**Comment by RalphBragg** [comment]
The security profile describes how to use the standards. The standards describe what the standards are. The two examples given here are a classic misunderstanding of who defines what.

A bank is responsible for the type, shape, format of access_tokens and refresh_tokens. The only two servers that are the intended audience of a Banks Issued Refresh Token is the Bank and the only intended audience of a bank access token is a banks api. 

What goes in a Banks Access Token is up to the Bank as the Bank knows what the Bank needs to give the required access to a TPP. Likewise what a Bank does to honour a refresh token and how it does that is up to a Bank. 

The request object is documented in the user guides. The id_token doesn't contain any non standard claims (unlike the UK which did which is why it required additional documentation. I'll make an explicit update to say 'there is nothing non-standard for the brazil ID Token please refer to OpenID Connect Core for example claims.

**Comment by RalphBragg** [comment]
As discussed on the security working group this morning, this is entirely in the domain of the banks.
@alex-siqueira  - any comments?

**Comment by RalphBragg** [comment]
Closing - invalid.
