### ISSUE TITLE
regulatory roles

### ISSUE THREAD

**Issue by andreborges01** [OpenBanking-Brasil/specs-seguranca#18]
As we don´t know which are the "regulatory roles" defined to Open Banking BR we don´t going to suggests complimentary scopes, but these are scopes, endpoints and permissions described to phase 2, as below:

**Scopes**
customers
accounts
creditcardaccounts
loans
financings
invoice-financings
unrranged-accounts-overdraft

**Permissions**
customers.personal.identifications.read
customers.personal.adicionalinfo.read
customers.business.identifications.read
customers.business.adicionalinfo.read
accounts.read
accounts.balance.read
accounts.transactions.read
accounts.overdfraft.limits.read
creditcardaccounts.read
creditcardaccounts.bills.read
creditcardaccounts.bills.transactions.read
creditcardaccounts.bills.limits.read
creditcardaccounts.transactions.read
loans.read
loans.payments.read
financings.read
financings.payments.read
invoice-financings.read
invoice-financings.payments.read
unrranged-accounts-overdraft.read
unrranged-accounts-overdraft.payments.read

Disclaimer:
We have no info if these scopes and permissions are the final version. We suggest you to check in the swagger.

**Comment by RalphBragg** [comment]
This mapping of 'accounts'  was provided by the Security team from consultation with the API team. 
https://openbanking-brasil.github.io/areadesenvolvedor/swagger/swagger_loans_apis.yaml An example API does not call out additional scope just the permission codes.

Multiple 'scopes' to permissions actually makes no sense and significantly complicates client management.
@ErickErick - can you please arrange a conversation with the security team so that they can understand the ramification of this especially as clients are assigned 'fixed scopes' when they register, if a Bank iteratively starts offering more APIs this significantly complicates client management for the banks.

**Comment by RalphBragg** [comment]
Will be discussed in todays security meeting.
Tx Renan.

**Comment by RalphBragg** [comment]
This has been worked around and won't be changed for implementers draft 1. the obligation is on the ASPSPs to make sure tokens are issued with the correct scope.
Changes were reflected in the latest version of the security profile.
