### ISSUE TITLE
Registered Signature key in Directory is not in JWKS URL

### ISSUE THREAD

**Issue by melothiagort** [OpenBanking-Brasil/specs-seguranca#202]
For the organization name (BCO DO EST. DE SE S.A.), Registration Number (BCO DO EST. DE SE S.A.), Organization ID (2d8829d2-4784-5a8a-9243-abd4a579000e).

The BRSEAL (Signature key) is correctly stored in the directory, but the JWKS URL is not showing the key
See the URL: https://keystore.directory.openbankingbrasil.org.br/2d8829d2-4784-5a8a-9243-abd4a579000e/3b2bc889-824f-4d8e-bb3d-d4d215689157/application.jwks. 

Instead, the Inactive URL is showing the key: https://keystore.directory.openbankingbrasil.org.br/2d8829d2-4784-5a8a-9243-abd4a579000e/inactive/application.jwks 

Could you please check whats is going on ?

**Comment by melothiagort** [comment]
Hello, @RalphBragg , @EkkeErick , any updates from the Directory ?

**Comment by EkkeErick** [comment]
Sorry, for that. I tried editing the comment and deleted it instead.

Everything is ok on the directory side and I understand that the certificate is already in a valid state on: https://keystore.directory.openbankingbrasil.org.br/2d8829d2-4784-5a8a-9243-abd4a579000e/3b2bc889-824f-4d8e-bb3d-d4d215689157/application.jwks.

As Ralph mentioned before the issue was caused because a few Certificates have been disabled because the CRL went down, which was unexpected behavior.

The Board has approved a proposal that will make certificates go to a soft_inactive state if the CRL is down. When the CRL is up and we can attest the validity of the certificate it will go back to an active state.
