### ISSUE TITLE
What is a JWT, JWE, JWS and JWK.

### ISSUE THREAD

**Issue by DeiGratia33** [OpenBanking-Brasil/specs-seguranca#31]
Third Party Provider End To End User Guide

- The JWS must be explained and pointed to the API definition of its usage.
The valid ciphers must be in accordance with https://www.bcb.gov.br/estabilidadefinanceira/exibenormativo?tipo=Instru%C3%A7%C3%A3o%20Normativa%20BCB&numero=99

**Comment by RalphBragg** [comment]
The TLS ciphers are already in accordance with this document. it just lists the BCP195, https://www.rfc-editor.org/rfc/rfc7525.txt,  recommended ciphers for TLS that support RSA. I will add a link to this document as it reinforces the position.

The FAPI Specification is actually a lot stronger than the BCB guide but nothing in the BCB guide would deviate from FAPI. 

The JWS / Application ciphers have not ben referenced by the BCB at all and so the most recommended ciphers from the IETF have been selected.

**Comment by RalphBragg** [comment]
The reference to the BCB security guide has been added in the security provisions of the security profile. There is no further action that anyone has to take from a cipher or tls point of view but it's good to be complete from a documentation view. 

JWS will be reviewed as part of the user guides.

**Comment by DeiGratia33** [comment]
We need to ensure the especs clarifies that even BCP and FAPI mention other ciphers, only the cipher below are allowed
'TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256'
'TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384

Also, for JWS we to clarify what type of JWS we are going to use, and mention that JWS is required per API resource indication.

**Comment by RalphBragg** [comment]
The BCP mentions 2 other ciphers correct. The two other ciphers are for EC certificates. The ICP Brazil doesn't issue EC certificates so they can't be used.

I've already updated this in the specification.

In terms of JWS can you give me an example of what you mean and where it should go? The signing and encryption requirements are already included for JWS/JWE.

**Comment by DeiGratia33** [comment]
The ICP-Brasil also uses EC, but for OpenBanking Brasil we are using RSA.

For the JWS we need to clarify the type of signature. If is dettached or not and put a note that the signature required or not goest inside of each API specification.

**Comment by RalphBragg** [comment]
OK - so the transport section is already covered (twice). The certicate profiles are only rsa and a section is included so that's closed,

In terms of JWS, payload signatures that makes a lot more sense now but again the mechanism for this belongs in the api specification. Is there a discussion on what mechanism will be used for payload signing?

I would suggest closing this ticket and opening a ticket explicitly on payload signing so it's clear what this request is about.

It's also worth a workshop / meeting because.

1. Sending messages as JWTs is far simpler than any of the message signing standards and this could be requested just by changing the content type from application/json to applicarion/json+jwt

[recommended]

2. There are a dozen different ways to create a signature for a normal http message however the ietf emerging standard is now this. https://www.ietf.org/archive/id/draft-ietf-httpbis-message-signatures-04.html

Its draft but it has the most wide spread support,

My personally preference is to skip the heart ache and just jwt the message but failing that then use this new draft standard.

**Comment by DeiGratia33** [comment]
Agreed. Let's close and open new one.

Members of the Security team started a proposal about detached signature based on UK, but without look to other options.

Not going too deep, all the resources are MTLS, so I am not finding a reason to a detached signature. But I am open to see pros and cons both ways.

**Comment by RalphBragg** [comment]
Closed in favour of a new ticket to discuss payload signing.
