### ISSUE TITLE
CNPJ and CPF for Consent Request

### ISSUE THREAD

**Issue by DeiGratia33** [OpenBanking-Brasil/specs-seguranca#64]
For phase2 of the Open Banking Brasil, the Consent API will be responsible to receive the CPF/CNPJ from the TPP, not requiring the TPP and ASPSP to process the CPF/CNPJ through the encrypted request object or PAR at the Authorization Server. 

We need to update the security-profile to support this decision.

**Comment by msauaia** [comment]
In the specification of the Authorization server, item 1 requires the implementation of signature and encryption of the request object (JWE). We understand that this was a requirement when there was a need to pass cpf / cnpj at the time of referral for authorization.

As there is no longer this need as (above), we understand that this item should be reformulated for JWS instead of JWE (only signed, nothing encrypted ).
