### ISSUE TITLE
Question: Refresh token expiration time

### ISSUE THREAD

**Issue by EllioSoares** [OpenBanking-Brasil/specs-seguranca#75]
Hello guys, there is a definition/recommendation for the refresh token expiration time to be equal to that of consent expiration time, right? So, since the consent expiration time could be any value until 12 months, I would like to know the compatibility of this topic with the software tools available from the vendors. For example, the Red Hat Keycloak permits only one value for the refresh token for each realm and that value will be used for all client-id in that realm.

It appears that this definition is not compatible with a lot of tools, if it is compatible with any right off the shelf. Any ideas of how to implement this point or it should be revised?

**Comment by RalphBragg** [comment]
Hi,

The requirement to invalidate access and refresh tokens when a TPP is no longer permitted to have them is a core requirement of any Authorization server. How you implement this is up to you but the requirement exists in all jurisdictions that have implemented Open Banking world wide.

Note that these jurisdictions are typically using a vendor that is FAPI 1 Advanced Certified which you can find on this list.
https://openid.net/certification/#FAPI_OPs you have many to choose from but unless you're using a FAPI 1 Advanced Certified Vendor that agrees that they can't meet this requirement for some reason I would personally be very surprised if the security team agreed to allow tokens to continue to be active after consent has expired.

**Comment by esachser** [comment]
Hi,

I believe @EllioSoares is talking about <https://github.com/OpenBanking-Brasil/specs-seguranca/blob/main/open-banking-brasil-financial-api-1_ID1.md#authorization-server-1>, item 1, who states that the refresh token shall be issued with the same validity than the consent *expirationDateTime*.
Revoking access and refresh tokens if the consent is revoked or gets expired seems logical and possible (and is the item 2), but create a constraint between consent and refresh token turns the AS to a very specialized solution.

It seems that the intention of the definition is to that the refresh tokens shall be valid at least for the time of the consent, and revoked if the consent get revoked or expired.

**Comment by RalphBragg** [comment]
@esachser - that is 100% percent correct. As more AS's support https://datatracker.ietf.org/doc/html/draft-ietf-oauth-rar
which will be required for FAPI 2.0. The less 'custom integrations' and more 'this is now standard' you will see. Support for RAR is still relatively low, support amongst FAPI complaint OP's for revoking the grant (which refresh,id_token and access_tokens) are based on is very high. Ask your vendors how to achieve this.

**Comment by DeiGratia33** [comment]
If we are unsure if the market will support to link the refresh expiration time to the consent, it would be better to replace:
shall issue refresh tokens with validity equal to the expirationDateTime defined on the linked Consent Resource;

to

**should** issue refresh tokens with validity equal to the expirationDateTime defined on the linked Consent Resource;

**Comment by RalphBragg** [comment]
Hi, This would be a normative change that would have to go into another iteration of the specifications. It's non breaking (except for the conformance harnesss) but it is a normative change. I'm surprised that security group would be happy with Authorisation Servers continuing to allow banks to issue Access Token (which is what happens when you use a refresh token) for access to resources that have expired. The 'scope' protection on existing resources becomes even more superfulous as you're essentially now saying 'shall grant or restrict access' based purely on consent resource. i.e Banks API Gateways will still be presented with tokens linked to consent that are expired? However, as it is the Banks themselves that are carrying this risk for their own services then it's up to them at the end of the day to ensure that data is only shared when there is a valid consent to do so.

perhaps making it clear (and obvious) 'shall only share access to resources when presented with an access token linked to an active and valid consent'.

**Comment by DeiGratia33** [comment]
The intention of the specification is to link the exactly time frame from a consent to the refresh token, but if this is not technically feasible for implementation, at least for the majorirty, we cannot include this as a mandatory item.

What it needs to be clear is the access tokens must be only issued if is linked to a valid consent, if the implementation ensure the refresh token expiration is linked to a consent, do it, if not, the implementation will need to add a validation step of the refresh token + consent expiration time before issue a new access token, because this way the refresh token expiration time will not represent the expiration of the consent.

**Comment by RalphBragg** [comment]
OK - so change this to a should (which will create a warn on the oidf conformance harness but warns are not a fail).

And publish a new version, it's not a breaking change but it would be a new version.

**Comment by RalphBragg** [comment]
Assigning to security team leads for a decision and implementation timeline impact.

**Comment by DeiGratia33** [comment]
We should sustain a refresh token time should be valid for the same timeframe of a linked consent. But the interpretation given is that the refresh token must have the same timeframe of a consent, what gives the initial concern raised by this issue.

**Comment by RalphBragg** [comment]
If the wording is unclear but the intent remains the same, perhaps someone could suggest alternative language? The net result should be that if a consent is expired an access token can not be 'refreshed' to obtain a new access token.

**Comment by mposolda** [comment]
> the Red Hat Keycloak permits only one value for the refresh token for each realm and that value will be used for all client-id in that realm.

Just a clarification, that this statement is not true at all and I am not sure how this was deducted? In Keycloak, each client has different refresh tokens. For example if client-a tries to use refresh token, which was issued for client-b, the Keycloak server will reject that refresh token attempt. Refresh token must be always issued for concrete client-id. Also even for refresh tokens for same client, each refresh token has different value. If all refresh tokens are same, then it won't be possible to have multiple refresh tokens for same client client-a and different users. Keycloak has support for the scenario that there is always only one valid refresh tokens for given client and given user session, which is available if better security is needed. In other words, each refresh token is single-use in this setup, hence client is enforced to "rotate" refresh tokens and always use the last refresh token from the last refresh.
