### ISSUE TITLE
Question: Mechanisms for client sends the reference to the lodging intents to the AS

### ISSUE THREAD

**Issue by msauaia** [OpenBanking-Brasil/specs-seguranca#76]
In the [documentation](https://github.com/OpenBanking-Brasil/specs-seguranca/blob/main/open-banking-brasil-financial-api-1_ID1.md#authorization-server), item 9 determines that the AS _shall support parameterized OAuth 2.0 resource scope consent as defined in clause 6.3.1 [[OIDF FAPI WG Lodging Intent Pattern](https://bitbucket.org/openid/fapi/src/master/Financial_API_Lodging_Intent.md)][LIWP]_.

However, if we are using OpenID Connect as a building block, why we must implement Parameterized Scope Values (6.3.1) instead of Claim (6.3.3), for example?

**Comment by RalphBragg** [comment]
The use of passing a claim for controlling access to resources was a Hack that i had to put into the UK Security Profile as it was the only technical means that could be used to convey this reference even though it went against what the claims and openid connect is used for.

https://openid.net/specs/openid-connect-core-1_0.html#Claims
5.  Claims
This section specifies how the Client can obtain Claims about the End-User and the Authentication event. It also defines a standard set of basic profile Claims. Pre-defined sets of Claims can be requested using specific scope values or individual Claims can be requested using the claims request parameter.

- Claims defines attributes about the user or their authentication
- scope defines and controls access to oauth 2.0 resources.
- this, mis use of claims, was communicated and accepted as not the correct approach (which is why it wasn't proliferated by Aus CDR and why Rich Authorization Specification was created.

"The OIDC claims parameter determines the claims shared between OP and RP via id token or userinfo. Using it to determine the claims in an access token has significant consequences:

The client needs to know what claims the RS needs to perform a certain action(s) and what claims will cause the RS to allow this action(s). This breaks the encapsulation of the interface between the AS and the RS. Suppose the RS needs more user data in a new revision, all clients needs to be notified and updated to request the right claims set in order to be able to access." -- Additional commentary copied from a discussion on this topic with Torsten Lodderstedt

**Comment by ediemerson-br** [comment]
If you have further question, you can create a service desk ticket.
https://servicedesk.openbankingbrasil.org.br/Login.jsp
