### ISSUE TITLE
OpenID - Request Objetct

### ISSUE THREAD

**Issue by FrancoPeluti** [OpenBanking-Brasil/specs-seguranca#88]
https://openid.net/specs/openid-connect-core-1_0.html#RequestObject
 
The iss value SHOULD be the Client ID of the RP, unless it was signed by a different party than the RP.
The aud value SHOULD be or include the OP's Issuer Identifier URL.
 
non-normative example:
   "iss": "s6BhdRkqt3",
   "aud": "https://server.example.com",
   "response_type": "code id_token",
   "client_id": "s6BhdRkqt3",

 

For the OPB BR, the RP client_id SHALL be the one registered by the OP ?
Is there a scenario that a different party may sign the Request Object ?
If so, how do we check it ?

**Comment by RalphBragg** [comment]
There's no scenario currently published where you should expect a request object to be signed by anyone other than the client itself

The requirements are tightened in FAPI 1 Advanced https://openid.net/specs/openid-financial-api-part-2-1_0.html which is what is layered on top of OpenID Connect Core.  The obligations are explicit for the AS and implicit for the 'Confidential Client'. The confidential client must issuer the signed request object which means they must sign it. Perhaps it could have done with an explicit clause but it is still covered.

This has been further clarified by the rules for IETF PAR - https://tools.ietf.org/id/draft-lodderstedt-oauth-par-00.html#rfc.section.3 if you're interested so that FAPI 2.0 it is explicit not an implicit.

If you're looking for processing rules start top down.
FAPI BR, FAPI 1 Advanced Final, FAPI 1 Base Final, FAPI 1 Core Errata 1, OAuth 2 RFC 6749

Don't start bottom up :-)
