### ISSUE TITLE
Consent transaction filters

### ISSUE THREAD

**Issue by samlarsen1** [OpenBanking-Brasil/specs-seguranca#99]
The transaction date filters defined in consent seem to only be documented in the consent swagger definition - the description is not definitive enough for people to understand.  I can't find any more guidance to point people to for this requirement.  

"transactionFromDateTime": "2021-01-01T00:00:00Z",
"transactionToDateTime": "2021-02-01T23:59:59Z"

Are these in scope?  We assume they are, they are in the consent spec - if so, we need more documentation to describe the general concepts of both consent transaction date filters and transaction API date filters.

**Comment by RalphBragg** [comment]
@GisAlmeida  - can you transfer this to the functional specs repo please. @samlarsen1  - as i understand they can all be optional but i don't remember where i read it. e.g you could have a minimum from but no end, or a unlimited from and a fixed end or you could have neither which would mean all data but i'll let @GisAlmeida provide the last word.

**Comment by samlarsen1** [comment]
Yes, i understand how they work from the UK, but there is no documentation of this in Brazil

**Comment by RalphBragg** [comment]
Sure - which is why i'm asking @GisAlmeida  to transfer this issue to the functional specifications repo so that she can add more details if required around the definitions.

Personally the descriptions seem OK to me as the behaviour is defined on the swagger, could you suggest what improvements you would want to make it clearer? 

Data e hora da transação inicial. Se não for preenchido, a transação terá a data aberta e a data será retornada com a primeira transação disponível. Uma string com data e hora conforme especificação RFC-3339, sempre com a utilização de timezone UTC(UTC time format).

Date and time of initial transaction. If not filled in, the transaction will be open date and the date will be returned with the first available transaction. A string with date and time according to RFC-3339 specification, always using the UTC timezone (UTC time format).

**Comment by samlarsen1** [comment]
Migrated to here: https://github.com/OpenBanking-Brasil/areadesenvolvedor/issues/158
